[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[volumes]]
mountPath = "/app/data"

